#!/bin/bash
#
#skript test kausta backupi tegemise kohta
tar -czf /home/andscript/skriptimine/praks4a/backup/test.tar.gz /home/andscript/skriptimine/praks4a/test
echo "kataloogi /home/andscript/skriptimine/praks4a/test/ backupi nimi on test.tar.gz ja ta asub /home/user/skriptimine/prask4a/backup/ kataloogis" #seletab ära mida praegu tehti
#
