#!/bin/bash
#
# Paaris ja mitte paaris aruvde kontrollija
#
echo "Sisesta suvaline täisarv: "
read a
if (($a % 2 == 0 ))
then
echo "$a on paarisarv."
else
echo "$a on paarituarv."
fi
#
# skripti lõpp
#
