#!/bin/bash
#
#Bussi ekskursiooni korraldaja tööriist
#
echo -n "Mitu inimest tuleb ekskursioonile? "
read a
echo -n "Mitu kohta on bussides? "
read b

bussidearv=$((($a / $b) + ( $a % $b > 0)))
echo "Ekskursiooni jaoks on teil vaja $bussidearv bussi"
# skripti lõpp
