#!/bin/bash
#
#Tordiabi
#
echo -n "Sisesta kandiku laius sentimeetrites: "
read a
echo -n "Sisesta kandiku pikkus sentimeetrites: "
read b
echo -n "Sisesta küpsise laius sentimeetrites: "
read c
echo -n "Sisesta küpsise pikkus sentimeetrites: "
read d
echo -n "Sisesta mitu kihti on tordil: "
read e
echo -n "Sisesta mitu küpsist on ühes pakis: "
read f

tpindala=`expr $a \* $b`
kpindala=`expr $c \* $d`
kiht=`expr $tpindala \/ $kpindala`
kupsised=`expr $kiht \* $e`
pakk=$((($kupsised/$f) + ($kupsised % $f > 0)))
echo "Tordi valmistamiseks on teil vaja $pakk pakki küpsiseid või $kupsised küpsist"
# skripti lõpp
